defaults:
  - _self_
  - problem: tsp_aco
  - llm_client: openai
  - override hydra/output: local

hydra:
  job:
    name: ${problem.problem_name}-${problem.problem_type}
    chdir: True

# The chosen algorithm
#algorithm: reevo # other options are "eoh", "ael"; some problems may not support "ael"; "coevolve"
# algorithm: coevolve

# Main GA loop parameters
max_fe: 100 # maximum number of function evaluations
pop_size: 10 # population size for GA
init_pop_size: 30 # initial population size for GA
mutation_rate: 0.5 # mutation rate for GA
timeout: 20 # timeout for evaluation of a single heuristic
diversify_init_pop: True # whether to diversify the initial population

# Algorithm specific configs
algorithm: coevolve  # coevolve, reevo, ael, eoh, moh, no_revolution
use_reflection: True  # use reflection or not
use_predictor: False  # use predictor or not
eval_ratio: 0.3  # max evaluation ratio of codes
use_serial: False  # use serial or not
finetune_predictor: False  # finetune predictor or not
#exp_obj_test_only: 10.590907757929719  # expected objective for test only, when reached, evolution will end. tsp200 10.597830984625435
#exp_obj_test_only: 13.0513379502685  # tsp300 expected objective for test only, when reached, evolution will end. 13.042729079273926
#exp_obj_test_only: 14.928442696680136  # expected objective for test only, when reached, evolution will end. tsp400 14.917518856945199
#exp_obj_test_only: 16.70012896149479  # tsp500 expected objective for test only, when reached, evolution will end. 16.691353004500908

#exp_obj_test_only: -22.47697614865646 # expected objective for test only, when reached, evolution will end. mkp_aco -22.448529577824807 -22.49881557308502 -22.47697614865646


#exp_obj_test_only: 23.160898208618164 # expected objective for test only, when reached, evolution will end. cvrp_pomo 23.058256149291992 23.160898208618164
#exp_obj_test_only: 21.38462257385254 # expected objective for test only, when reached, evolution will end. cvrp_lehd 21.38462257385254 21.2584228515625

embedding_llm_model: 'text-embedding-ada-002'
embedding_end_point: ''  # e.g. https://api.bianxie.ai/v1
embedding_api_key: ''  # e.g. sk-xxxxxxxxxxxxxx
