description: Optimizing the Multi-Knapsack Problem through Hybrid Adaptive Sampling
  and Iterative Reinforcement Learning Techniques, Leveraging Ensemble of Genetic
  Algorithms and Stochastic Local Search Algorithms for Enhanced Performance in Prized
  Item Subset Selection.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
