description: Design a hybrid optimization heuristic for the Multiple Knapsack Problem
  (MKP) that incorporates adaptive stochastic sampling. The heuristic should utilize
  dynamic fitness evaluation and robust perturbation techniques to refine candidate
  solutions iteratively. This approach will balance exploration and exploitation,
  ensuring effective prize maximization while respecting stringent weight constraints,
  and will be supported by a clear metaheuristic framework with well-defined adaptive
  sampling strategies and perturbation algorithms.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
