description: The proposed heuristic for the Capacitated Vehicle Routing Problem (CVRP)
  integrates a targeted hybrid evolutionary strategy with a precise local search module.
  The hybrid evolutionary component utilizes a state-of-the-art genetic algorithm
  with adaptive selection, efficient crossover, and selective mutation to explore
  the solution space effectively. The local search module focuses on neighborhood
  exploration using a swap-insertion heuristic and a capacity-aware 2-opt algorithm,
  ensuring both route length optimization and capacity adherence. The heuristic incorporates
  a normalization technique to level the demand of customer nodes and applies a constraint-aware
  optimization process to efficiently manage vehicle capacities. Additionally, the
  algorithm dynamically adjusts the neighborhood structure based on evolutionary progress
  to balance exploration and exploitation. This streamlined approach provides a clear
  and direct route to efficient and capacity-constrained solutions, avoiding unnecessary
  complexity and ensuring a robust optimization process.
func_name: heuristics
obj_type: min
problem_name: cvrp_pomo
problem_size: 200
problem_type: nco
