description: Developing an integrated optimization framework for the Multi-Objective
  Knapsack Problem (MOKP) that employs a deep reinforcement learning-based real-time
  decision-making system. This system is supported by an adaptive constraint-driven
  filtering mechanism to ensure multi-dimensional feasibility in dynamic environments.
  Additionally, a particle swarm optimization (PSO) algorithm is integrated for evolutionary
  swarm intelligence, aiming to strike a balance between computational efficiency
  and adaptability. The framework should aim to maximize the total prize collection
  while adhering to multi-dimensional maximum weight constraints, and it should be
  evaluated on its ability to consistently produce near-optimal solutions with high
  fitness scores in scenarios where the problem constraints evolve over time.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
