description: Optimizing the selection of item subsets in a multi-dimensional knapsack
  problem by integrating adaptive metaheuristic-based stochastic sampling. This approach
  aims to maximize combined reward through enhanced exploration of the solution space,
  balancing exploitation and exploration while respecting stringent weight limits.
  The algorithm prioritizes high-value item combinations and dynamically adjusts heuristics
  to ensure compliance with dimension-specific weight constraints, mitigating the
  risk of local optima and improving overall performance.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
