description: Designing an optimization heuristic for the Multi-Knapsack Problem (MKP)
  that incorporates stochastic solution sampling and ensemble learning. The heuristic
  should leverage a combination of Genetic Algorithms (GAs) and Stochastic Local Search
  (SLS) algorithms to identify an optimal subset of items for each knapsack, aiming
  to maximize the total prize while respecting the weight constraints. The approach
  should prioritize clarity in algorithm design and implementation, utilizing adaptive
  sampling techniques to explore diverse solution spaces effectively.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
