description: Develop a novel optimization heuristic for a time-sensitive dynamic capacitated
  vehicle routing problem (DCVRP) that minimizes total route distances while enforcing
  vehicle capacities without exceeding them. The heuristic should incorporate a combination
  of constraint programming techniques, a dynamic window approach to handle real-time
  changes, and a multi-objective evolutionary algorithm to ensure robustness and adaptability.
  The heuristic must employ node partitioning to optimize path decomposition and use
  demand relaxation to manage dynamic changes in node demands and vehicle capacities.
  The goal is to achieve a real-time solution that balances the trade-off between
  minimizing route distances and maintaining optimal vehicle load distribution, while
  maintaining clarity in the capacity and demand specifications and employing precise
  algorithmic components and performance criteria.
func_name: heuristics
obj_type: min
problem_name: cvrp_pomo
problem_size: 200
problem_type: nco
