description: Develop a probabilistic optimization heuristic tailored for the Multiple
  Knapsack Problem (MKP) that integrates adaptive stochastic sampling, real-time fitness
  assessment, and multi-objective decision-making. This heuristic will utilize a dynamic
  probability model for item selection, which weights the likelihood of including
  items based on a normalized value-to-weight ratio and a heuristic assessment of
  feasibility considering the remaining knapsack capacities. The algorithm will iteratively
  refine candidate solutions by combining intelligent perturbation techniques and
  heuristic-driven search strategies to balance the exploration of the solution space
  with the exploitation of the most promising solutions. The core goal is to maximize
  the cumulative reward across multiple knapsacks while ensuring a balance between
  computational efficiency and solution robustness.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
