description: Develop a hybrid heuristic leveraging a probabilistic Genetic Algorithm
  (GA) for initial item subset exploration combined with a sophisticated Stochastic
  Local Search (SLS) algorithm to iteratively refine the solution space, ultimately
  maximizing total prize accumulation while ensuring compliance with stringent weight
  limitations across a multi-knapsack setup.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
