description: Utilizing hybrid metaheuristics to optimize the selection of item subsets
  in Multi-Knapsack Problems (MKP), focusing on dynamic weight distribution and adaptive
  heuristic sampling to enhance prize maximization and constraint adherence.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
