description: Enhancing the Traveling Salesman Problem (TSP), we introduce a cutting-edge
  hybrid evolutionary algorithm that integrates a guided local search with intelligent
  parameter tuning and an evolving neighborhood structure. This algorithm utilizes
  a precision heuristic matrix for swift distance estimations, aiming to exceed a
  fitness threshold of 10.617516362484723. By combining heuristic-driven initialization,
  dynamic mutation strategies, and adaptive selection criteria, the algorithm fosters
  an optimized search space, leading to the discovery of superior travel routes.
func_name: heuristics
obj_type: min
problem_name: tsp_gls
problem_size: 200
problem_type: gls
