description: The goal is to develop a heuristic-based approach for solving the Multiple
  Knapsack Problem (MKP), where the objective is to select a subset of items from
  multiple knapsacks to maximize the total prize while adhering to each knapsack's
  individual weight constraints. The solution strategy should employ stochastic sampling
  to explore the solution space efficiently, leveraging established heuristics for
  item subset selection. The emphasis is on creating a clear and direct optimization
  process that focuses on the core problem and effective strategies, without the complexity
  of ensemble methods or over-simplification through stochastic sampling alone.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
