description: Integrate a probabilistic selection mechanism with a metaheuristic framework
  to tackle the Multi-Knapsack Problem, optimizing for maximum prize while respecting
  weight capacities. This approach should leverage dimensionality reduction for normalized
  item data, implement an adaptive sampling routine for iterative improvement, and
  utilize a dynamic fitness assessment for real-time optimization. By combining a
  hybrid evolutionary algorithm with local search techniques, this strategy aims to
  achieve a balanced exploration-exploration trade-off, ensuring efficient prize maximization
  under stringent weight constraints.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
