description: The objective is to develop a robust optimization algorithm for the Multiple
  Knapsack Problem (MKP), which involves selecting item subsets to maximize total
  prize collection while adhering to strict multi-dimensional weight constraints.
  The algorithm should incorporate a dynamic adaptive weight allocation mechanism
  to efficiently partition knapsacks, and utilize a refined heuristic-based sampling
  strategy to ensure precise subset selection. This approach aims to enhance problem-solving
  efficiency by focusing on the dynamics of the MKP, promoting diversity in solutions,
  and applying normalization techniques to optimize the allocation process.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
