_target_: utils.llm_client.openai.OpenAIClient

model: gpt-3.5-turbo # LLM model
temperature: 1.0  # temperature for chat completion
api_key: ${oc.env:CUSTOM_API_KEY,null}
base_url: https://api.feidaapi.com