description: The TSP is addressed through a hybrid algorithm that synergistically
  blends adaptive guided local search with state-of-the-art metaheuristics like simulated
  annealing and path-swapping. This method harnesses the potential of a multi-objective
  evolutionary algorithm to foster diversity in the solution space, continually enhancing
  solutions via innovative mutation and crossover mechanisms. The algorithm optimally
  utilizes both the Manhattan distance heuristic and the direct application of the
  distance matrix for efficient traversal of diverse solution landscapes. Advanced
  adaptive parameter tuning and constraint-driven pruning strategies are incorporated
  to maximize computational efficiency and surpass a fitness threshold of 10.60242549294038,
  yielding superior TSP solutions through a balanced approach that optimizes both
  local neighborhood structures and global search efficiency, ensuring a robust and
  scalable solution framework.
func_name: heuristics
obj_type: min
problem_name: tsp_gls
problem_size: 200
problem_type: gls
