description: The objective is to devise a sophisticated optimization algorithm for
  the Multiple Knapsack Problem (MKP) that achieves maximum prize collection through
  a dynamic allocation of item subsets, constrained by multi-dimensional weight limits.
  The algorithm shall incorporate a self-adaptive weight distribution system to enhance
  partitioning efficiency, and apply a precision-based heuristic sampling method for
  targeted subset selection. The approach will focus on leveraging the evolving nature
  of the MKP to foster solution diversity, and implement normalization techniques
  to fine-tune the weight allocation process, ensuring a balanced and efficient optimization
  strategy.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
