description: "The goal is to develop a refined heuristic for the hybrid Capacitated\
  \ Vehicle Routing Problem (hCVRP) that efficiently optimizes logistics routes while\
  \ strictly adhering to vehicle capacity constraints. The heuristic should integrate\
  \ the following key components:\n\n1. Precise Demand Handling:\n   - Implement a\
  \ demand normalization algorithm to accurately reflect the total demand of nodes\
  \ on potential routes.\n   - Develop a cumulative demand mask that dynamically assesses\
  \ the total demand along potential routes, ensuring load balancing.\n\n2. Capacity\
  \ Constraint Prioritization:\n   - Create an edge feasibility mask to rigorously\
  \ evaluate the impact of adding an edge on a vehicle's capacity before incorporating\
  \ it into a route.\n   - Enforce capacity-based prioritization by considering the\
  \ load distribution and vehicle capacity when selecting edges.\n\n3. Clear Edge\
  \ Evaluation:\n   - Define a clear and objective evaluation method for edges, ensuring\
  \ that the chosen paths contribute to efficient and feasible routes.\n   - Utilize\
  \ this evaluation to determine the optimal sequence of nodes for each vehicle.\n\
  \n4. Optimization Strategies:\n   - Adopt direct optimization techniques for route\
  \ feasibility without compromising solution quality.\n   - Prioritize simplicity\
  \ and clarity in demand and capacity management, avoiding ambiguity and complexity.\n\
  \nThe resulting heuristic should be designed to navigate the complexities of hCVRP\
  \ by utilizing the cumulative demand for route prioritization and focusing on computational\
  \ efficiency, ensuring robust and effective routing plans for fleet operations."
func_name: heuristics
obj_type: min
problem_name: cvrp_lehd
problem_size: 200
problem_type: nco
