description: The Traveling Salesman Problem (TSP) is tackled using a guided local
  search algorithm that integrates a genetic algorithm with simulated annealing and
  a sophisticated heuristic function. This algorithm optimizes the shortest path by
  minimizing edge distances and employing local heuristics. It employs adaptive parameter
  tuning and multi-criteria optimization to iteratively refine solutions, aiming to
  surpass a fitness score of 10.61187021517528 through a hybrid optimization strategy
  that leverages both global and local search principles, and incorporates a heuristic
  that not only minimizes the sum of the longest edges in each node pair but also
  calculates the minimum distance from each node to all others.
func_name: heuristics
obj_type: min
problem_name: tsp_gls
problem_size: 200
problem_type: gls
