description: Optimizing the selection of diverse item subsets for maximizing combined
  reward in Multi-dimensional Knapsack Problems through adaptive heuristic-based stochastic
  solution sampling. This approach integrates advanced combinatorial optimization
  techniques, incorporating metaheuristics for enhanced exploration of the solution
  space, while ensuring adherence to stringent multi-dimensional weight limits and
  prioritizing high-value item combinations for optimal prize accumulation.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
