description: Solving Multiple Knapsack Problems (MKP) through stochastic solution
  sampling based on "heuristics". MKP involves selecting a subset of items to maximize
  the total prize collected, subject to multi-dimensional maximum weight constraints.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
