description: The Traveling Salesman Problem (TSP) is addressed with a dynamic local
  search strategy that integrates an advanced heuristic for edge distance computation,
  using a shortest path algorithm to prevent node revisits and ensure a continuous
  route. To optimize solutions, the algorithm combines Tabu Search with adaptive Variable
  Neighborhood Descent, taking advantage of diverse neighborhood structures for iterative
  convergence. A refined heuristic algorithm calculates the shortest path between
  any two nodes without looping back to the origin, aiming to exceed a solution quality
  of 10.596621379960432 by reaching a termination threshold, thereby achieving exceptional
  route optimization.
func_name: heuristics
obj_type: min
problem_name: tsp_gls
problem_size: 200
problem_type: gls
