description: Develop a probabilistic algorithm for the Multi-Knapsack Problem (MKP)
  that leverages a dynamic ranking system to prioritize items with the highest value-to-weight
  ratio. This system should utilize adaptive stochastic sampling techniques to iteratively
  select items, optimizing their distribution across knapsacks while rigorously enforcing
  weight constraints. The algorithm must implement an advanced exploration strategy
  that systematically identifies and incorporates the most valuable and lightweight
  items, ensuring optimal load distribution and adherence to individual knapsack weight
  limits.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
