description: The objective is to design a state-of-the-art algorithm for solving the
  Multiple Knapsack Problem (MKP), focusing on maximizing total prize collection under
  stringent multi-dimensional weight constraints. The algorithm must incorporate a
  dynamic adaptive weight allocation mechanism, which intelligently partitions knapsacks
  to enhance efficiency. It should utilize a refined heuristic-based sampling strategy,
  specifically the Max-Utility heuristic, to guarantee precise item subset selection.
  This approach aims to foster solution diversity by exploring the problem space effectively
  and applying normalization techniques to streamline the allocation process, ensuring
  a robust and optimized solution to the MKP.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
