description: 'The problem description is as follows:


  Design a novel heuristic algorithm for solving Multiple Knapsack Problems (MKP),
  which involves selecting an optimal subset of items from various knapsacks to maximize
  total prize collection while adhering to multi-dimensional weight constraints. The
  algorithm must integrate stochastic sampling, adaptive sampling strategies, and
  a dynamic fitness evaluation system to iteratively refine candidate solutions. Key
  features include multi-objective optimization, robust perturbation techniques, and
  a balanced approach to exploration and exploitation. The algorithm''s performance
  will be assessed through comprehensive testing using standard benchmark instances,
  focusing on maximizing prize collection while minimizing computational effort, and
  evaluating results based on objective function values, computational time, and robustness
  against varying knapsack capacities and item distributions.'
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
