description: Optimizing the selection of diverse items for a multi-knapsack scenario
  through a hybrid metaheuristic approach that incorporates adaptive weighting and
  dynamic partitioning strategies. This approach leverages a stochastic sampling mechanism
  to strategically select subsets of items, maximizing the reward-to-weight ratio
  while adhering to multi-dimensional weight constraints and ensuring optimal item
  diversity and normalization.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
