description: Design a hybrid optimization algorithm for the Multi-dimensional Knapsack
  Problem (MKP) that utilizes a genetic algorithm (GA) for diversity and a Simulated
  Annealing (SA) for refined local search. The algorithm should employ a value-to-weight
  ratio-based heuristic to prioritize items, ensuring maximum total value while respecting
  multi-dimensional weight and volume constraints. The genetic algorithm will use
  a fitness function that considers both constraint compliance and total value, with
  selection based on normalized value-to-weight ratios. The GA will employ specific
  operators such as tournament selection, single-point crossover, and mutation for
  evolution. The Simulated Annealing component will refine the solutions by allowing
  occasional violations of constraints at higher temperatures, which will be reduced
  over generations to exploit promising regions. Termination will be based on a predefined
  number of generations, a convergence threshold, or when no improvement is observed
  over a set number of iterations. The algorithm will be evaluated on its ability
  to maximize the average solution value, minimize constraint violations, and optimize
  computational efficiency, with the goal of achieving a balance between exploration
  and exploitation.
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
