description: 'Problem Description:

  Develop an optimization algorithm that employs stochastic solution sampling combined
  with a hybrid approach, incorporating both evolutionary algorithms and stochastic
  local search methods, to solve the Multiple Knapsack Problem (MKP). The goal is
  to maximize the total value of items selected, while adhering to the weight constraints
  of each knapsack. This approach will leverage clear and direct strategies, avoiding
  unnecessary complexity and providing explicit details on the techniques used, such
  as genetic algorithms and local search, to achieve effective item subset selection
  and enhanced performance in the MKP solution space.'
func_name: heuristics
obj_type: max
problem_name: mkp_aco
problem_size: 100
problem_type: aco
